
This is a Dockerfile for the ubi10/openjdk-21:1.24 image.


## START target image ubi10/openjdk-21:1.24
## \
    FROM registry.redhat.io/ubi10/ubi@sha256:864f6b94f9f64a059aed7dc8f95b0854f5eb06140f95aed32300da63a1f7877d
    #FROM registry.access.redhat.com/ubi10/ubi-minimal@sha256:04140c8d78c6c6915b5c1fdad2f16d10eac3630c3339999ccdf659d8c903be50


    USER root

###### START module 'jboss.container.user:2.0'
###### \
        # Copy 'jboss.container.user' module content
        COPY modules/jboss.container.user /tmp/scripts/jboss.container.user
        # Switch to 'root' user for package management for 'jboss.container.user' module defined packages
        USER root
        RUN : \
        # Install packages defined in the 'jboss.container.user' module
        && microdnf --setopt=install_weak_deps=0 --setopt=tsflags=nodocs install -y shadow-utils \
            && rpm -q shadow-utils \
        && :

        # Set 'jboss.container.user' module defined environment variables
        ENV \
            GECOS="Default user" \
            HOME="/home/default" \
            UID="185" \
            USER="default"
        # Custom scripts from 'jboss.container.user' module
        USER root
        RUN sh -x "/tmp/scripts/jboss.container.user/configure.sh"
###### /
###### END module 'jboss.container.user:2.0'

###### START module 'jboss.container.openjdk:0'
###### \
###### /
###### END module 'jboss.container.openjdk:0'

###### START module 'jboss.container.openjdk.jre:21'
###### \
        # Switch to 'root' user for package management for 'jboss.container.openjdk.jre' module defined packages
        USER root
        RUN : \
        # Install packages defined in the 'jboss.container.openjdk.jre' module
        && microdnf --setopt=install_weak_deps=0 --setopt=tsflags=nodocs install -y java-21-openjdk-headless \
            && rpm -q java-21-openjdk-headless \
        && :

        # Set 'jboss.container.openjdk.jre' module defined environment variables
        ENV \
            JAVA_HOME="/usr/lib/jvm/java-21-openjdk" \
            JAVA_VENDOR="openjdk" \
            JAVA_VERSION="21" \
            JBOSS_CONTAINER_OPENJDK_JRE_MODULE="/opt/jboss/container/openjdk/jre"
        # Set 'jboss.container.openjdk.jre' module defined labels
        LABEL \
            org.jboss.product="openjdk" \
            org.jboss.product.openjdk.version="21" \
            org.jboss.product.version="21"
###### /
###### END module 'jboss.container.openjdk.jre:21'

###### START module 'jboss.container.openjdk.jdk:21'
###### \
        # Switch to 'root' user for package management for 'jboss.container.openjdk.jdk' module defined packages
        USER root
        RUN : \
        # Install packages defined in the 'jboss.container.openjdk.jdk' module
        && microdnf --setopt=install_weak_deps=0 --setopt=tsflags=nodocs install -y java-21-openjdk-devel \
            && rpm -q java-21-openjdk-devel \
        && :

        # Set 'jboss.container.openjdk.jdk' module defined environment variables
        ENV \
            JBOSS_CONTAINER_OPENJDK_JDK_MODULE="/opt/jboss/container/openjdk/jdk"
###### /
###### END module 'jboss.container.openjdk.jdk:21'

###### START module 'jboss.container.maven.module:3.8'
###### \
        # Copy 'jboss.container.maven.module' module content
        COPY modules/jboss.container.maven.module /tmp/scripts/jboss.container.maven.module
        # Custom scripts from 'jboss.container.maven.module' module
        USER root
        RUN sh -x "/tmp/scripts/jboss.container.maven.module/configure.sh"
###### /
###### END module 'jboss.container.maven.module:3.8'

###### START module 'jboss.container.maven:3.9.21'
###### \
        # Copy 'jboss.container.maven' module content
        COPY modules/jboss.container.maven /tmp/scripts/jboss.container.maven
        # Switch to 'root' user for package management for 'jboss.container.maven' module defined packages
        USER root
        RUN : \
        # Install packages defined in the 'jboss.container.maven' module
        && microdnf --setopt=install_weak_deps=0 --setopt=tsflags=nodocs install -y maven-openjdk21 \
            && rpm -q maven-openjdk21 \
        && :

        # Set 'jboss.container.maven' module defined environment variables
        ENV \
            JBOSS_CONTAINER_MAVEN_39_MODULE="/opt/jboss/container/maven/39/" \
            MAVEN_VERSION="3.9"
        # Custom scripts from 'jboss.container.maven' module
        USER root
        RUN sh -x "/tmp/scripts/jboss.container.maven/configure.sh"
###### /
###### END module 'jboss.container.maven:3.9.21'

###### START module 'jboss.container.s2i.core:9.0'
###### \
        # Copy 'jboss.container.s2i.core' module content
        COPY modules/jboss.container.s2i.core /tmp/scripts/jboss.container.s2i.core
        # Switch to 'root' user for package management for 'jboss.container.s2i.core' module defined packages
        USER root
        RUN : \
        # Install packages defined in the 'jboss.container.s2i.core' module
        && microdnf --setopt=install_weak_deps=0 --setopt=tsflags=nodocs install -y findutils rsync \
            && rpm -q findutils rsync \
        && :

        # Set 'jboss.container.s2i.core' module defined environment variables
        ENV \
            JBOSS_CONTAINER_S2I_CORE_MODULE="/opt/jboss/container/s2i/core/" \
            S2I_SOURCE_DEPLOYMENTS_FILTER="*.jar quarkus-app"
        # Set 'jboss.container.s2i.core' module defined labels
        LABEL \
            io.openshift.s2i.destination="/tmp" \
            io.openshift.s2i.scripts-url="image:///usr/libexec/s2i" \
            org.jboss.container.deployments-dir="/deployments"
        # Custom scripts from 'jboss.container.s2i.core' module
        USER root
        RUN sh -x "/tmp/scripts/jboss.container.s2i.core/configure.sh"
###### /
###### END module 'jboss.container.s2i.core:9.0'

###### START module 'jboss.container.java.proxy:2.0'
###### \
        # Copy 'jboss.container.java.proxy' module content
        COPY modules/jboss.container.java.proxy /tmp/scripts/jboss.container.java.proxy
        # Set 'jboss.container.java.proxy' module defined environment variables
        ENV \
            JBOSS_CONTAINER_JAVA_PROXY_MODULE="/opt/jboss/container/java/proxy"
        # Custom scripts from 'jboss.container.java.proxy' module
        USER root
        RUN sh -x "/tmp/scripts/jboss.container.java.proxy/configure.sh"
###### /
###### END module 'jboss.container.java.proxy:2.0'

###### START module 'jboss.container.java.jvm:1.0'
###### \
        # Copy 'jboss.container.java.jvm' module content
        COPY modules/jboss.container.java.jvm /tmp/scripts/jboss.container.java.jvm
        # Set 'jboss.container.java.jvm' module defined environment variables
        ENV \
            JBOSS_CONTAINER_JAVA_JVM_MODULE="/opt/jboss/container/java/jvm"
        # Custom scripts from 'jboss.container.java.jvm' module
        USER root
        RUN sh -x "/tmp/scripts/jboss.container.java.jvm/configure.sh"
###### /
###### END module 'jboss.container.java.jvm:1.0'

###### START module 'jboss.container.util.logging:1.0'
###### \
        # Copy 'jboss.container.util.logging' module content
        COPY modules/jboss.container.util.logging /tmp/scripts/jboss.container.util.logging
        # Set 'jboss.container.util.logging' module defined environment variables
        ENV \
            JBOSS_CONTAINER_UTIL_LOGGING_MODULE="/opt/jboss/container/util/logging/"
        # Custom scripts from 'jboss.container.util.logging' module
        USER root
        RUN sh -x "/tmp/scripts/jboss.container.util.logging/configure.sh"
###### /
###### END module 'jboss.container.util.logging:1.0'

###### START module 'jboss.container.maven.default:1.0'
###### \
        # Copy 'jboss.container.maven.default' module content
        COPY modules/jboss.container.maven.default /tmp/scripts/jboss.container.maven.default
        # Switch to 'root' user for package management for 'jboss.container.maven.default' module defined packages
        USER root
        RUN : \
        # Install packages defined in the 'jboss.container.maven.default' module
        && microdnf --setopt=install_weak_deps=0 --setopt=tsflags=nodocs install -y findutils \
            && rpm -q findutils \
        && :

        # Set 'jboss.container.maven.default' module defined environment variables
        ENV \
            JBOSS_CONTAINER_MAVEN_DEFAULT_MODULE="/opt/jboss/container/maven/default/"
        # Custom scripts from 'jboss.container.maven.default' module
        USER root
        RUN sh -x "/tmp/scripts/jboss.container.maven.default/configure.sh"
###### /
###### END module 'jboss.container.maven.default:1.0'

###### START module 'jboss.container.maven.s2i:1.0'
###### \
        # Copy 'jboss.container.maven.s2i' module content
        COPY modules/jboss.container.maven.s2i /tmp/scripts/jboss.container.maven.s2i
        # Switch to 'root' user for package management for 'jboss.container.maven.s2i' module defined packages
        USER root
        RUN : \
        # Install packages defined in the 'jboss.container.maven.s2i' module
        && microdnf --setopt=install_weak_deps=0 --setopt=tsflags=nodocs install -y tar \
            && rpm -q tar \
        && :

        # Set 'jboss.container.maven.s2i' module defined environment variables
        ENV \
            JBOSS_CONTAINER_MAVEN_S2I_MODULE="/opt/jboss/container/maven/s2i"
        # Custom scripts from 'jboss.container.maven.s2i' module
        USER root
        RUN sh -x "/tmp/scripts/jboss.container.maven.s2i/configure.sh"
###### /
###### END module 'jboss.container.maven.s2i:1.0'

###### START module 'jboss.container.util.pathfinder:1.0'
###### \
        # Copy 'jboss.container.util.pathfinder' module content
        COPY modules/jboss.container.util.pathfinder /tmp/scripts/jboss.container.util.pathfinder
        # Set 'jboss.container.util.pathfinder' module defined environment variables
        ENV \
            JBOSS_CONTAINER_UTIL_PATHFINDER_MODULE="/opt/jboss/container/util/pathfinder"
        # Custom scripts from 'jboss.container.util.pathfinder' module
        USER root
        RUN sh -x "/tmp/scripts/jboss.container.util.pathfinder/configure.sh"
###### /
###### END module 'jboss.container.util.pathfinder:1.0'

###### START module 'jboss.container.java.run:1.0'
###### \
        # Copy 'jboss.container.java.run' module content
        COPY modules/jboss.container.java.run /tmp/scripts/jboss.container.java.run
        # Set 'jboss.container.java.run' module defined environment variables
        ENV \
            JAVA_DATA_DIR="/deployments/data" \
            JBOSS_CONTAINER_JAVA_RUN_MODULE="/opt/jboss/container/java/run"
        # Custom scripts from 'jboss.container.java.run' module
        USER root
        RUN sh -x "/tmp/scripts/jboss.container.java.run/configure.sh"
###### /
###### END module 'jboss.container.java.run:1.0'

###### START module 'jboss.container.java.s2i.bash:1.0'
###### \
        # Copy 'jboss.container.java.s2i.bash' module content
        COPY modules/jboss.container.java.s2i.bash /tmp/scripts/jboss.container.java.s2i.bash
        # Switch to 'root' user for package management for 'jboss.container.java.s2i.bash' module defined packages
        USER root
        RUN : \
        # Install packages defined in the 'jboss.container.java.s2i.bash' module
        && microdnf --setopt=install_weak_deps=0 --setopt=tsflags=nodocs install -y rsync \
            && rpm -q rsync \
        && :

        # Set 'jboss.container.java.s2i.bash' module defined environment variables
        ENV \
            JBOSS_CONTAINER_JAVA_S2I_MODULE="/opt/jboss/container/java/s2i"
        # Custom scripts from 'jboss.container.java.s2i.bash' module
        USER root
        RUN sh -x "/tmp/scripts/jboss.container.java.s2i.bash/configure.sh"
###### /
###### END module 'jboss.container.java.s2i.bash:1.0'

###### START module 'jboss.container.util.licenses:1.0'
###### \
        # Copy 'jboss.container.util.licenses' module content
        COPY modules/jboss.container.util.licenses /tmp/scripts/jboss.container.util.licenses
        # Custom scripts from 'jboss.container.util.licenses' module
        USER root
        RUN sh -x "/tmp/scripts/jboss.container.util.licenses/execute.sh"
###### /
###### END module 'jboss.container.util.licenses:1.0'

###### START image 'ubi10/openjdk-21:1.24'
###### \
        # Set 'ubi10/openjdk-21' image defined environment variables
        ENV \
            JBOSS_IMAGE_NAME="ubi10/openjdk-21" \
            JBOSS_IMAGE_VERSION="1.24" \
            LANG="C.utf8" \
            PATH="$PATH:"/usr/libexec/s2i""
        # Set 'ubi10/openjdk-21' image defined labels
        LABEL \
            com.redhat.component="openjdk-21-ubi10-container" \
            com.redhat.license_terms="https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI" \
            description="Source To Image (S2I) image for Red Hat OpenShift providing OpenJDK 21" \
            io.cekit.version="4.17.0.dev0" \
            io.k8s.description="Platform for building and running plain Java applications (fat-jar and flat classpath)" \
            io.k8s.display-name="Java Applications" \
            io.openshift.tags="builder,java" \
            maintainer="Red Hat OpenJDK <openjdk@redhat.com>" \
            name="ubi10/openjdk-21" \
            org.opencontainers.image.documentation="https://rh-openjdk.github.io/redhat-openjdk-containers/" \
            org.opencontainers.image.revision="ubi10" \
            org.opencontainers.image.source="https://github.com/rh-openjdk/redhat-openjdk-containers" \
            org.opencontainers.image.source="https://github.com/rh-openjdk/redhat-openjdk-containers" \
            summary="Source To Image (S2I) image for Red Hat OpenShift providing OpenJDK 21" \
            usage="https://rh-openjdk.github.io/redhat-openjdk-containers/" \
            version="1.24"
        # Exposed ports in 'ubi10/openjdk-21' image
        EXPOSE 8080 8443
###### /
###### END image 'ubi10/openjdk-21:1.24'



    # Switch to 'root' user and remove artifacts and modules
    USER root
    RUN rm -rf "/tmp/scripts" "/tmp/artifacts"
    # Clear package manager metadata
    RUN microdnf clean all \
    && rm -rf "/var/cache/yum" "/var/lib/dnf" "/var/cache/apt" "/var/cache/dnf"
    # Define the user
    USER 185
    # Define the working directory
    WORKDIR /home/default
    # Define run cmd
    CMD ["/usr/libexec/s2i/run"]
## /
## END target image
